apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.component_id | dump}}
  {%- if values.description %}
  description: ${{values.description | dump}}
  {%- endif %}
  annotations:
    circleci.com/project-slug: github/${{values.destination.owner + "/" + values.destination.repo}}
spec:
  type: service
  lifecycle: experimental
  owner: ${{values.owner | dump}}
