version: '2.1'
orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.3
jobs:
  test-cluster:
    docker:
      - image: cimg/python:3.10
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
    steps:
      - kubernetes/install:
          kubectl-version: v1.22.0
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
      - run:
          command: |
            kubectl get services
            kubectl create deployment springapplication --image=280214392207.dkr.ecr.us-east-1.amazonaws.com/springapplication:'${{values.app_image_name}}'-latest
          name: Test cluster
workflows:
  deployment:
    jobs:
      - aws-eks/create-cluster:
          cluster-name: '${{values.eks_cluster_name}}'
      - test-cluster:
          cluster-name: '${{values.eks_cluster_name}}'
          requires:
            - aws-eks/create-cluster
   #   - aws-eks/delete-cluster:
   #       cluster-name: my-eks-demo
   #       requires:
   #         - test-cluster
